# This Makefile is generated by omake: https://github.com/ouonline/omake.git

CC := gcc

ifeq ($(debug), y)
	CFLAGS += -g
else
	CFLAGS += -O2 -DNDEBUG
endif

AR := ar

TARGET := libmath_shared.so libmath_static.a

.PHONY: all clean distclean

all: $(TARGET)

omake_dep_0.xorshift32.c.o: xorshift32.c
	$(CC) $(CFLAGS) -Wall -Werror -Wextra -fPIC -c $< -o $@

omake_dep_0.mt19937_64.c.o: mt19937_64.c
	$(CC) $(CFLAGS) -Wall -Werror -Wextra -fPIC -c $< -o $@

omake_dep_0.splitmix64.c.o: splitmix64.c
	$(CC) $(CFLAGS) -Wall -Werror -Wextra -fPIC -c $< -o $@

omake_dep_0.xorshift64.c.o: xorshift64.c
	$(CC) $(CFLAGS) -Wall -Werror -Wextra -fPIC -c $< -o $@

omake_dep_0.mt19937_32.c.o: mt19937_32.c
	$(CC) $(CFLAGS) -Wall -Werror -Wextra -fPIC -c $< -o $@

omake_dep_0.xoshiro256ss.c.o: xoshiro256ss.c
	$(CC) $(CFLAGS) -Wall -Werror -Wextra -fPIC -c $< -o $@

math_shared_OBJS := omake_dep_0.xoshiro256ss.c.o omake_dep_0.xorshift64.c.o omake_dep_0.splitmix64.c.o omake_dep_0.mt19937_32.c.o omake_dep_0.mt19937_64.c.o omake_dep_0.xorshift32.c.o

libmath_shared.so: $(math_shared_OBJS)
	$(CC) $(CFLAGS) -fPIC -Wextra -Werror -Wall -shared -o $@ $^

math_static_OBJS := omake_dep_0.xoshiro256ss.c.o omake_dep_0.xorshift64.c.o omake_dep_0.splitmix64.c.o omake_dep_0.mt19937_32.c.o omake_dep_0.mt19937_64.c.o omake_dep_0.xorshift32.c.o

libmath_static.a: $(math_static_OBJS)
	$(AR) rc $@ $^

clean:
	rm -f $(TARGET) $(math_shared_OBJS) $(math_static_OBJS)

distclean:
	$(MAKE) clean
